[package]
name = "search-trees"
version = "0.1"
lean_version = "leanprover-community/lean:3.22.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "40da087f75b542cffa5d2116b522e57c1a7a66b1"}
